export default {
  commands: [
    "",
    "Available commands:",
    "> about",
    "> home",
    "> projects",
    "> jobs",
    "> stack",
  ],
  loading: [
    "Resume loading...",
    "Version 0.21 beta",
    "PENTIUM S CPU at 133 Mhz",
    "Memory test: 64 MB ok",
    "",
    "Skills loaded:",
    "Javascript/Typescript",
    "PHP, MySQL",
    "React, Vue",
    "Laravel, Redis",
    "Booting...",
  ],
  home: ["bzzzz", "bzzzz", "bzzzz", "bzzzz", ""],
  about: [
    "Hi! My name is Bohdan Kovalevskyi",
    "I'm a fullstack web developer.",
    "",
    "Once I stuck in the shower because the shampoo bottle sais: Lather, Rainse, Repeat.",
    "",
    "I always put two glasses on my bedside table before going to sleep. A full one, in case I gets thirsty, and an empty one, in case I don't.",
    "",
    "What is my favourite hangout place? Foo Bar",
    "",
    "Javascript spoied me, now I always do promises, but never callback.",
    "",
  ],
  jobs: [
    "Since 2019 I've been working as a fullstack developer at Devoltex OU.",
    "",
    "2016-2018 - System operator",
    "",
    "2015-2016 - Freelance wordpress developer",
  ],
  projects: [
    "Currently in progress - Wordilla.com - SaaS project management platform for content writing teams.",
    "Stack:",
    "Frontend: React using hooks, Context, TypeScript, Webpack",
    "Backend: PHP Laravel for API, MariaDB, Docker, Linux, Nginx",
    "",
    "2018-2022 - Orderwriting.com - freelance writing marketplace with over 30.000 completed orders.",
    "Stack:",
    "Frontend: Vue.js",
    "Backend: PHP Laravel MVC, MySQL, Redis, Docker, Linux, Nginx)",
    "",
    "2021 - Psyroom.online - online psychological consultation platform. Find a psychologist, book time, get helped.",
    "Stack:",
    "Frontend: Vue.js",
    "Backend: PHP Laravel MVC, MySQL, Docker, Linux, Nginx)",
    "",
    "and dozens of wordpress websites",
  ],
  stack: [
    "Teachnologies I've used to work with:",
    "",
    "JavaScript",
    "TypeScript",
    "React (hooks)",
    "Vue.js",
    "PHP",
    "Laravel",
    "REST API",
    "MySQL/MariaDB",
    "Linux",
    "Docker",
    "Nginx",
    "Redis",
    "GitHub",
  ],
};
