export default {
  commands: [
    "Available commands:",
    "> stack",
    "> jobs",
    "> projects",
    "> test",
    "> help",
  ],
  loading: [
    "Resume loading...",
    "Version 0.21 beta",
    "PENTIUM S CPU at 133 Mhz",
    "Memory test: 64 MB ok",
    "",
    "Skills loaded:",
    "Javascript/Typescript",
    "PHP, MySQL",
    "React, Vue",
    "Laravel, Redis",
    "Booting from Hard Disk...",
  ],
  home: [
    "Hi! My name is Dan Levskyi",
    "",
    "Once I stuck in the shower because the shampoo bottle sais: Lather, Rainse, Repeat.",
    "",
    "I always put two glasses on my bedside table before going to sleep. A full one, in case I gets thirsty, and an empty one, in case I don't.",
    "",
    "What is my favourite hangout place? Foo Bar",
    "",
    "Javascript spoied me, now I always do promises, but never callback.",
    "",
    "I don't see women as objects. I consider eact to be a class of her own.",
    "",
  ],
  jobs: ["2019-2022: Devoltex OU - Fullstack developer"],
  stack: ["• .NET Framework, переходим постепенно на .NET Core:"],
  help: ["• .NET Framework, переходим постепенно на .NET Core:"],
};
